list_example_json = [
    {
        "id": 1,
        "title": "Annual Company Meeting",
        "description": "A meeting to discuss the company's yearly progress and plans.",
        "start_time": "13 Dec 2024 08:00",
        "end_time": "13 Dec 2024 10:00",
        "location": "Headquarters",
        "organizer": "Digital_Dragon (digital.dragon@test.com)",
        "participants": 5,
    },
    {
        "id": 4,
        "title": "Project Kickoff",
        "description": "Initial meeting to kick off a new project with all stakeholders.",
        "start_time": "13 Dec 2024 12:00",
        "end_time": "13 Dec 2024 14:00",
        "location": "Room 301",
        "organizer": "John_Doe (john.doe@test.com)",
        "participants": 7,
    },
    {
        "id": 6,
        "title": "Workshop: AI in Healthcare",
        "description": "A workshop discussing the applications of AI in the healthcare industry.",
        "start_time": "15 Dec 2024 08:00",
        "end_time": "15 Dec 2024 10:00",
        "location": "Lab 5",
        "organizer": "John_Doe (john.doe@test.com)",
        "participants": 5,
    },
    {
        "id": 8,
        "title": "Client Presentation",
        "description": "Presentation of project progress and future plans to the client.",
        "start_time": "22 Dec 2024 13:00",
        "end_time": "22 Dec 2024 14:30",
        "location": "Client Office",
        "organizer": "SkyWalker89 (sky.walker@test.com)",
        "participants": 0,
    },
    {
        "id": 7,
        "title": "Webinar: Future of Blockchain",
        "description": "An online seminar exploring the future developments in blockchain technology.",
        "start_time": "20 Jan 2025 09:00",
        "end_time": "20 Jan 2025 10:30",
        "location": "Online",
        "organizer": "John_Doe (john.doe@test.com)",
        "participants": 5,
    },
]
